<style>
  .clear { clear: both }
  .container {
    width: 1200px;
    padding: 10px;
  }
  #post {
    width: 300px;
    height: 320px;
    background: black;
    float: left;
    margin-left: 90px;
    margin-right: 100px;
  }
  #post1 {
    width: 300px;
    height: 320px;
    background: black;
    float: left;
    margin-right: 90px;
  }
  #sidebar {
    width: 300px;
    height: 320px;
    background: black;
    float: right;
    /* margin-right: 90px */
  }
  .footer-links
  {
    padding-left:0;
    list-style:none
  }
  .footer-links li
  {
    display:block
    
  }
  .footer-links a
  {
    color:white
  }
  .footer-links a:active,.footer-links a:focus,.footer-links a:hover
  {
    color:#3366cc;
    text-decoration:none;
  }
  .footer-links.inline li
  {
    display:inline-block
  }
</style>
<div id="content" class="container">
  <div id="post" style="color: white;">
    <img style="width: 74px; height: 74px;" src="https://media-cdn.tripadvisor.com/media/photo-s/1b/6e/77/44/mydeli-homemade-pasta.jpg" alt="">
    <p class="text-justify">20 Carrochan Rd, Balloch, Alexandria G83 8EG, UK 69QJ+2F Alexandria, United Kingdom</p>
    <p class="text-justify">phone- +91 123 456 789 0, +91 <br>123 456 789 0</p>
    <p class="text-justify">email- support@pizzon.com</p>
  </div>
  <div id="post1" style="color: white;">
    <h6 style="font-size: 20px;">OPEN HOURS</h6>
    <p>Mon - Tues: 6.00 Am - 10.00 Pm <br>Wednes - Thurs: 6.00 Am - 10.00 Pm <br>Launch: Everyday <br>Sunday: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<mark style="background-color: orange; color: white;">&nbsp;Closed&nbsp; </mark></p>
  </div>
  <div id="sidebar" style="color: white;">
    <h6 style="font-size: 20px;">USEFUL LINKS</h6>
    <ul class="footer-links">
      <li><a>About Us</a></li>
      <li><a>Privacy Policy</a></li>
      <li><a>Order Tracking</a></li>
      <li><a>Warranty And Services</a></li>
      <li><a>About</a></li>
      <li><a>Contact Us</a></li>
      <li><a>Wishlist</a></li>
    </ul>
  </div>
</div>